name: tmdb_movies
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6

  enhanced_paginated_view: ^1.0.7
  easix: ^1.0.1

  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  path_provider: ^2.1.2
  talker_bloc_logger: ^2.4.0
  equatable: ^2.0.5

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  dio: ^5.4.2+1
  talker_dio_logger: ^2.4.0

  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  flutter_dotenv: ^5.1.0

  connectivity_plus: ^5.0.2
  get_it: ^7.6.7
  go_router: ^13.1.0
  flutter_svg: ^2.0.6
  intl: ^0.19.0
  flutter_hooks: ^0.20.4
  animate_do: ^3.3.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  flutter_easyloading: ^3.0.5
  lottie: ^3.1.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8


flutter:

 
  uses-material-design: true

  assets:
    - assets/
    - .env

  